name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installer uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
        
      - name: Configurer Python
        run: uv python install

      - name: Exécuter la suite de tests
        run: uv run pytest

      